# Generated by Django 6.0.7 on 2026-08-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_unique_together'),
        ('inventory', '0005_stockmovement_related_sale_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_items', to='catalog.product'),
        ),
    ]
