# Generated by Django 6.0.7 on 2026-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_retailer_phone_per_tenant'),
        ),
    ]
